// star-data.js - Generated from merged PRs
// This file is auto-generated by GitHub Actions on each PR merge

window.STAR_DATA = [
  {
    id: 1,
    issueNumber: 1,
    title: "Add login form",
    description: "User authentication with email and password",
    position: { x: 10, y: 20, z: 5 },
    color: "blue",
    size: 8,
    brightness: 1.0,
    pulse: false,
    priority: "standard",
    linesChanged: 78,
    files: 3,
    commitHash: "abc123...",
    mergedAt: "2024-02-19T10:30:00Z",
    builtBy: "user1",
  },
  {
    id: 2,
    issueNumber: 2,
    title: "Add dark mode toggle",
    description: "Switch between light and dark themes",
    position: { x: -15, y: 10, z: -8 },
    color: "green",
    size: 5,
    brightness: 0.9,
    pulse: false,
    priority: "standard",
    linesChanged: 42,
    files: 2,
    commitHash: "def456...",
    mergedAt: "2024-02-19T11:45:00Z",
    builtBy: "user2",
  },
  {
    id: 3,
    issueNumber: 3,
    title: "Add user profile page",
    description: "Display user information and settings",
    position: { x: 5, y: -12, z: 15 },
    color: "blue",
    size: 12,
    brightness: 0.95,
    pulse: true,
    priority: "express",
    linesChanged: 156,
    files: 5,
    commitHash: "ghi789...",
    mergedAt: "2024-02-19T13:00:00Z",
    builtBy: "user3",
  },
  {
    id: 4,
    issueNumber: 4,
    title: "Add password reset",
    description: "Email-based password recovery",
    position: { x: -8, y: 25, z: -3 },
    color: "green",
    size: 10,
    brightness: 0.85,
    pulse: false,
    priority: "priority",
    linesChanged: 98,
    files: 4,
    commitHash: "jkl012...",
    mergedAt: "2024-02-19T14:15:00Z",
    builtBy: "user1",
  },
  {
    id: 5,
    issueNumber: 5,
    title: "Add API rate limiting",
    description: "Prevent abuse with request throttling",
    position: { x: 20, y: -5, z: -12 },
    color: "purple",
    size: 7,
    brightness: 0.8,
    pulse: false,
    priority: "standard",
    linesChanged: 65,
    files: 2,
    commitHash: "mno345...",
    mergedAt: "2024-02-19T15:30:00Z",
    builtBy: "user4",
  },
]

// Color mappings for feature types
window.COLOR_MAPPINGS = {
  blue: "#3b82f6",    // UI Features
  green: "#22c55e",   // Logic & APIs
  yellow: "#eab308",  // Data & Models
  purple: "#a855f7",  // Infrastructure
  pink: "#ec4899",    // Tests
}
