import { NextResponse } from 'next/server'

// Mock data - will be replaced with actual data from database/API later
const MOCK_STAR_DATA = [
  {
    id: 1,
    issueNumber: 1,
    title: "Add login form",
    description: "User authentication with email and password",
    position: { x: 10, y: 20, z: 5 },
    color: "blue",
    size: 8,
    brightness: 1.0,
    pulse: false,
    priority: "standard",
    linesChanged: 78,
    files: 3,
    commitHash: "abc123...",
    mergedAt: "2024-02-19T10:30:00Z",
    builtBy: "user1",
  },
  {
    id: 2,
    issueNumber: 2,
    title: "Add dark mode toggle",
    description: "Switch between light and dark themes",
    position: { x: -15, y: 10, z: -8 },
    color: "green",
    size: 5,
    brightness: 0.9,
    pulse: false,
    priority: "standard",
    linesChanged: 42,
    files: 2,
    commitHash: "def456...",
    mergedAt: "2024-02-19T11:45:00Z",
    builtBy: "user2",
  },
  {
    id: 3,
    issueNumber: 3,
    title: "Add user profile page",
    description: "Display user information and settings",
    position: { x: 5, y: -12, z: 15 },
    color: "blue",
    size: 12,
    brightness: 0.95,
    pulse: true,
    priority: "express",
    linesChanged: 156,
    files: 5,
    commitHash: "ghi789...",
    mergedAt: "2024-02-19T13:00:00Z",
    builtBy: "user3",
  },
  {
    id: 4,
    issueNumber: 4,
    title: "Add password reset",
    description: "Email-based password recovery",
    position: { x: -8, y: 25, z: -3 },
    color: "green",
    size: 10,
    brightness: 0.85,
    pulse: false,
    priority: "priority",
    linesChanged: 98,
    files: 4,
    commitHash: "jkl012...",
    mergedAt: "2024-02-19T14:15:00Z",
    builtBy: "user1",
  },
  {
    id: 5,
    issueNumber: 5,
    title: "Add API rate limiting",
    description: "Prevent abuse with request throttling",
    position: { x: 20, y: -5, z: -12 },
    color: "purple",
    size: 7,
    brightness: 0.8,
    pulse: false,
    priority: "standard",
    linesChanged: 65,
    files: 2,
    commitHash: "mno345...",
    mergedAt: "2024-02-19T15:30:00Z",
    builtBy: "user4",
  },
  {
    id: 6,
    issueNumber: 42,
    title: "Add dark mode toggle",
    description: "Users can switch between light and dark themes with persistent preference",
    position: { x: -10, y: -15, z: 20 },
    color: "blue",
    size: 14,
    brightness: 0.9,
    pulse: true,
    priority: "express",
    linesChanged: 89,
    files: 9,
    commitHash: "a1b2c3d",
    mergedAt: "2024-02-19T11:45:00Z",
    builtBy: "Claude",
  },
  {
    id: 7,
    issueNumber: 43,
    title: "Implement user authentication",
    description: "Add email/password login with JWT tokens and session management",
    position: { x: 15, y: 10, z: -15 },
    color: "green",
    size: 11,
    brightness: 0.85,
    pulse: false,
    priority: "priority",
    linesChanged: 5,
    files: 3,
    commitHash: "m0n1o2p",
    mergedAt: null,
    builtBy: "Claude",
  },
  {
    id: 8,
    issueNumber: 44,
    title: "Create payment integration",
    description: "Integrate Stripe for $1 payments on feature requests",
    position: { x: -20, y: 5, z: 10 },
    color: "purple",
    size: 13,
    brightness: 0.88,
    pulse: false,
    priority: "priority",
    linesChanged: 10,
    files: 10,
    commitHash: "q3r4s5t",
    mergedAt: null,
    builtBy: "Claude",
  },
  {
    id: 9,
    issueNumber: 45,
    title: "Add real-time queue tracking",
    description: "Live updates of build queue with WebSocket connections",
    position: { x: 0, y: -20, z: 0 },
    color: "blue",
    size: 9,
    brightness: 0.92,
    pulse: false,
    priority: "standard",
    linesChanged: 8,
    files: 8,
    commitHash: "y9z0a1b",
    mergedAt: "2024-02-19T10:00:00Z",
    builtBy: "Claude",
  },
]

const COLOR_MAPPINGS = {
  blue: "#3b82f6",    // UI Features
  green: "#22c55e",   // Logic & APIs
  yellow: "#eab308",  // Data & Models
  purple: "#a855f7",  // Infrastructure
  pink: "#ec4899",    // Tests
}

export async function GET() {
  return NextResponse.json({
    stars: MOCK_STAR_DATA,
    colorMappings: COLOR_MAPPINGS,
  })
}
