#!/usr/bin/env node

/**
 * Build script for generating star-data.js from GitHub PR metadata
 * This script is run by GitHub Actions on each PR merge
 */

const fs = require('fs')
const path = require('path')

// Configuration
const OUTPUT_FILE = path.join(__dirname, '..', 'js', 'star-data.js')

// Sample PR data (in production, this would come from GitHub API)
// For now, we'll keep the existing star-data.js unchanged
// When GitHub Actions is set up, it will:
// 1. Fetch all merged PRs from the repo
// 2. Extract metadata (issue number, commit hash, lines changed, file types)
// 3. Calculate deterministic position from commit hash
// 4. Map file types to colors
// 5. Generate star-data.js

console.log('🌌 Building ChaosCraft Galaxy...')

// Check if star-data.js exists
if (fs.existsSync(OUTPUT_FILE)) {
  console.log('✅ star-data.js already exists')
  console.log(`   Location: ${OUTPUT_FILE}`)
} else {
  console.log('⚠️  star-data.js not found, creating sample data...')
  createSampleStarData()
}

function createSampleStarData() {
  const sampleData = `// star-data.js - Generated from merged PRs
// This file is auto-generated by GitHub Actions on each PR merge

window.STAR_DATA = [
  {
    id: 1,
    issueNumber: 1,
    title: "Add login form",
    description: "User authentication with email and password",
    position: { x: 10, y: 20, z: 5 },
    color: "blue",
    size: 8,
    brightness: 1.0,
    pulse: false,
    priority: "standard",
    linesChanged: 78,
    files: 3,
    commitHash: "abc123...",
    mergedAt: "2024-02-19T10:30:00Z",
    builtBy: "user1",
  },
]

// Color mappings for feature types
window.COLOR_MAPPINGS = {
  blue: "#3b82f6",    // UI Features
  green: "#22c55e",   // Logic & APIs
  yellow: "#eab308",  // Data & Models
  purple: "#a855f7",  // Infrastructure
  pink: "#ec4899",    // Tests
}
`

  fs.writeFileSync(OUTPUT_FILE, sampleData, 'utf8')
  console.log('✅ Created sample star-data.js')
}

console.log('🚀 Build complete!')
